apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: billyean/node:1.0.0
        name: node
        ports:
        - containerPort: 8080
